name: Compile to .hex

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install QMK and dependencies
        run: |
          sudo apt-get install -y python3-pip git
          pip3 install setuptools
          python3 -m pip install --user qmk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Prepare layouts
        run: |
          qmk setup -y
          qmk config user.keymap=tpanum
          qmk new-keymap -kb kinesis
          qmk new-keymap -kb ergodox_ez

          cp kinesis/keymap.c ~/qmk_firmware/keyboards/kinesis/keymaps/tpanum/
          cp ergodox/keymap.c ~/qmk_firmware/keyboards/ergodox_ez/keymaps/tpanum/

      - name: Compile layouts
        run: |
          qmk compile -kb ergodox_ez -km tpanum
          qmk compile -kb kinesis/stapelberg -km tpanum
          ls -lha ~/qmk_firmware/.build
          cp ~/qmk_firmware/.build/*.hex .


      - name: Define variables
        id: vars
        run: |
          echo ::set-output name=release_name::$(TZ=Europe/Copenhagen date)
          echo ::set-output name=release_info::$(git log --pretty=short -n 1)
          echo ::set-output name=kinesis_filename::$(echo kinesis_$(git log --pretty=format:'%h' -n 1).hex)
          echo ::set-output name=ergodox_filename::$(echo ergodox_$(git log --pretty=format:'%h' -n 1).hex)
      - name: Create release
        id: latest_draft
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.vars.outputs.release_name }}
          body: ${{ steps.vars.outputs.release_info }}
          draft: true
      - name: Publish Ergodox hex files
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_draft.outputs.upload_url }}
          asset_path: "./ergodox_ez_tpanum.hex"
          asset_name: ${{ steps.vars.outputs.ergodox_filename }}
          asset_content_type: application/octet-stream

      - name: Publish Kinesis hex files
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_draft.outputs.upload_url }}
          asset_path: "./kinesis_stapelberg_tpanum.hex"
          asset_name: ${{ steps.vars.outputs.kinesis_filename }}
          asset_content_type: application/octet-stream
